### PR TITLE
Pass GH_TOKEN to the changelog generation step

### PR DESCRIPTION
**Pull request by eigenraven**
Forgot to copy in the token when moving things around the yaml.

### CODE REVIEW

**Comment by glowredman** [comment]
Isn't it needed in the "Publish to Maven, Modrinth and CurseForge" step too?

**Comment by eigenraven** [comment]
Gradle shouldn't be using the github api, so no

**Comment by glowredman** [comment]
Maybe I fundamentally missunderstand something here but won't https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/master/build.gradle#L668 have no access to the file then?

**Comment by eigenraven** [comment]
GH_TOKEN is used to authenticate HTTP requests made to the github api, which is done by the `gh` command. The previous step uses `gh` to save the changelog into a file, reading a file doesn't require any sort of api token

**Comment by glowredman** [comment]
Ahhh 😅 - I somehow was under the impression that you were making the step able to access the `CHANGELOG_FILE` env var...

**Review by mitchej123 — APPROVED** [review]

**Pull request merged**
